# Generated by Django 5.1.2 on 2024-12-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='mostrar',
            field=models.IntegerField(default=0),
        ),
    ]
