# Generated by Django 5.1.2 on 2024-12-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0002_productos_mostrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
