# Generated by Django 5.1.2 on 2024-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0003_alter_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='mostrar',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
