# Generated by Django 5.1.2 on 2024-11-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0004_usuario_productos_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
