# Generated by Django 5.1.2 on 2024-11-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatesApp', '0006_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imgproduct/'),
        ),
    ]
